/**
 * Legal-only ingest taxonomy. Not part of the shared private-evidence primitive.
 */

const { LEGAL_DOCUMENT_TYPE } = require('./legalTitleContract');

const ALLOWED_LEGAL_DOCUMENT_TYPES = Object.freeze([
  LEGAL_DOCUMENT_TYPE.TITLE_REGISTER,
  LEGAL_DOCUMENT_TYPE.TITLE_PLAN,
  LEGAL_DOCUMENT_TYPE.LEASE,
  LEGAL_DOCUMENT_TYPE.TRANSFER,
  LEGAL_DOCUMENT_TYPE.CONVEYANCE,
  LEGAL_DOCUMENT_TYPE.DEED,
  LEGAL_DOCUMENT_TYPE.DEED_OF_VARIATION,
  LEGAL_DOCUMENT_TYPE.RESTRICTION,
  LEGAL_DOCUMENT_TYPE.COVENANT_DOCUMENT,
  LEGAL_DOCUMENT_TYPE.EASEMENT_DOCUMENT,
  LEGAL_DOCUMENT_TYPE.CHARGE_DOCUMENT,
  LEGAL_DOCUMENT_TYPE.PLANNING_AGREEMENT,
  LEGAL_DOCUMENT_TYPE.OFFICIAL_COPY,
  LEGAL_DOCUMENT_TYPE.OTHER,
  LEGAL_DOCUMENT_TYPE.OTHER_LEGAL_DOCUMENT,
  LEGAL_DOCUMENT_TYPE.UNKNOWN,
]);

const REJECTED_FOR_LEGAL_INGEST = Object.freeze({
  SURVEY: 'SURVEY',
  INSPECTION_REPORT: 'INSPECTION_REPORT',
  QUOTE: 'QUOTE',
  INVOICE: 'INVOICE',
  PROJECT_BUDGET: 'PROJECT_BUDGET',
});

function normalizeLegalDocumentType(value) {
  if (value == null || value === '') return LEGAL_DOCUMENT_TYPE.UNKNOWN;
  const key = String(value).trim().toUpperCase();
  if (REJECTED_FOR_LEGAL_INGEST[key]) {
    throw new Error('DOCUMENT_TYPE_NOT_ACCEPTED');
  }
  if (key === 'OTHER_LEGAL_DOCUMENT') return LEGAL_DOCUMENT_TYPE.OTHER_LEGAL_DOCUMENT;
  if (!LEGAL_DOCUMENT_TYPE[key] || !ALLOWED_LEGAL_DOCUMENT_TYPES.includes(key)) {
    throw new Error('INVALID_DOCUMENT_TYPE');
  }
  return key;
}

module.exports = {
  ALLOWED_LEGAL_DOCUMENT_TYPES,
  REJECTED_FOR_LEGAL_INGEST,
  normalizeLegalDocumentType,
};
