-- Migration Tracker Table
-- This table tracks which migrations have been applied to the database
-- DO NOT EDIT THIS FILE MANUALLY - It is managed by the migration runner

CREATE TABLE IF NOT EXISTS schema_migrations (
  id SERIAL PRIMARY KEY,
  migration_name VARCHAR(255) UNIQUE NOT NULL,
  applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  applied_by VARCHAR(100) DEFAULT CURRENT_USER
);

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_schema_migrations_name ON schema_migrations(migration_name);

-- Add comment
COMMENT ON TABLE schema_migrations IS 'Tracks which database migrations have been applied';

